//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserMgmtMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApplication
    {
        public int UserApplicationId { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationLink { get; set; }
    }
}
